app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,EmailField,SubmitField,BooleanField
from wtforms.validators import DataRequired,Length,EqualTo,Email
from wtforms.widgets import TextArea
from flask_wtf.file import FileField,FileAllowed
from wtforms import StringField,TextAreaField, SubmitField,ValidationError,DateTimeField,SelectField,IntegerField,DateField
from wtforms.validators import DataRequired,Email,Length
from flask_login import current_user
from ..model import User

class UpdateProfile(FlaskForm):
    username = StringField('Enter Your Username', validators=[DataRequired()])
    email = StringField('Email Address', validators=[DataRequired(),Email()])
    bio = TextAreaField('Write a brief bio about you.',validators = [DataRequired()])
    profile_picture = FileField('profile picture', validators=[FileAllowed(['jpg','png'])])
    submit = SubmitField('Update')

    def validate_email(self,email):
        if email.data != current_user.email:
            if User.query.filter_by(email = email.data).first():
                raise ValidationError("The Email has already been taken!")
    
    def validate_username(self, username):
        if username.data != current_user.username:
            if User.query.filter_by(username = username.data).first():
                raise ValidationError("The username has already been taken")

class OrderForm(FlaskForm):
    Details = TextAreaField('Order details',validators=[DataRequired()])
    devilerydate= DateField('Delivery date')
    submit = SubmitField('Order Now')


class ReviewForm(FlaskForm):
    review=TextAreaField('Leave a Review', validators=[DataRequired()])
    submit = SubmitField('Submit Details')


class SelectServiceForm(FlaskForm):
    category=SelectField('choose service category', choices=[('Photography', 'photography'), ('Catering', 'catering'), ('Transport', 'transport')])
    budget=IntegerField('Enter amount not less than Ksh 50,000', validators=[DataRequired(),Length(min=50000)])
    delivery_date=DateTimeField('Expected date of delivery', validators=[DataRequired()])
    submit=SubmitField('Submit Details')


class AddServiceForm(FlaskForm):
    category=SelectField('choose service category', choices=[('Photograpy', 'photograpy'), ('Catering', 'catering'), ('Transport', 'transport')])
    cost=IntegerField('Enter service cost in kenyan shillings', validators=[DataRequired()])
    service_pic=FileField('profile picture', validators=[FileAllowed(['jpg','png'])])
    description=TextAreaField("Give a brief description of the service")
    submit=SubmitField('Submit')

app/__init__.py
from flask import Flask
from .config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_bootstrap import Bootstrap


bootstrap=Bootstrap()
login_manager = LoginManager()
db = SQLAlchemy()


migrate=Migrate()
#Initializing application
def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    from .main import main
    from .auth import auth
    app.register_blueprint(main)
    app.register_blueprint(auth)

    bootstrap.init_app(app)

    db.init_app(app)
    login_manager.init_app(app)
    migrate = Migrate(app, db)

    return app
    

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template,redirect,url_for,abort,request,flash
from app.model import User,Order,Review,Service
from .forms import UpdateProfile,ReviewForm,OrderForm,SelectServiceForm,AddServiceForm
from .. import db
from flask_login import login_required,current_user
# from ..emails import mail_message
import secrets
import os
from PIL import Image
from app.main import main


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_filename = random_hex + f_ext
    picture_path = os.path.join('app/static/images', picture_filename)
    form_picture.save(picture_path)
    
    output_size = (200, 200)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)
    return picture_filename

@main.route('/')
def index():
    title='Bridalbliss'
    
    page = request.args.get('page',1, type = int )
    services = Service.query.order_by(Service.user_id.desc()).paginate(page = page, per_page = 3)
    return render_template('index.html',services=services )

@main.route('/about.html')
def about():
    return render_template('about.html')    

@main.route('/team.html')
def team():
    return render_template('team.html')       

@main.route('/profile',methods = ['POST','GET'])
@login_required
def profile():
    form = UpdateProfile()
    if form.validate_on_submit():
        if form.profile_picture.data:
            picture_file = save_picture(form.profile_picture.data)
            current_user.profile_pic_path = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash('Successfully updated your profile')
        return redirect(url_for('main.profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.bio.data = current_user.bio
    # profile_pic_path = url_for('static',filename = 'images/'+ current_user.profile_pic_path) 
    return render_template('profile/profile.html',  form = form)

@main.route('/user/<name>/updateprofile', methods = ['POST','GET'])
@login_required
def updateprofile(name):
    form = UpdateProfile()
    user = User.query.filter_by(username = name).first()
    if user == None:
        abort(404)
    if form.validate_on_submit():
        user.bio = form.bio.data
        user.save()
        return redirect(url_for('.profile',name = name))
    return render_template('profile/updateprofile.html',form =form)

@main.route('/addservice/<int:user_id>',methods=['GET','POST'])
@login_required
def addservice(user_id):
    user=User.query.get(user_id)
    
    form=AddServiceForm()
    if form.validate_on_submit():
            service=Service(category=form.category.data,cost=form.cost.data)
            service.save()
            return redirect('main.index')
    return render_template('service/addservice.html',form=form, title='Add service')

@main.route('/dispservices',methods=['GET','POST'])
def dispservices():
    services=Service.query.all()
    return render_template('displayservice.html', services=services)

@main.route('/filterservice',methods=['GET','POST'])
@login_required

def filterservice():
    form=SelectServiceForm()
    if form.validate_on_submit():
        budget=form.budget.data
        affordable_services = db.session.query(Service).filter(Service.cost<=budget).all()
    
    return render_template('budget/budget.html',form=form, budgets=affordable_services)

@main.route('/makeorder/<int:serv_id>',methods=['GET','POST'])
@login_required
def makeorder(serv_id):
    if current_user.is_authenticated:
        form=OrderForm()
        if form.validate_on_submit():
            order=Order(details=form.Details.data,user_id=current_user.id)
            order.save()
            return redirect(url_for('main.index'))
    return render_template('orders/makeorder.html',form=form)

@main.route('/orders/<int:user_id>')
@login_required
def orders(user_id):
    user=User.query.get(user_id)

    allorders=Order.query.filter_by(user_id=user_id).all()
    return render_template('orders/orders.html', orders=allorders,user=user)

@main.route('/deleteorder/<int:id>',methods=['GET','POST'])
@login_required
def deleteorder(id):
    order=Order.query.filter_by(id=id).first()
    order.delete()
    return redirect('main.orders')

@main.route('/review/<int:serv_id>',methods=['GET','POST'])
@login_required 
def review(serv_id):
    form=ReviewForm()
    if form.validate_on_submit():
        review=Review(content=form.review.data)
        return redirect('main.index')

    return render_template('reviews.html',form=form)


    

app/templates/about.html
{% extends 'base.html'%}

{% block content%}

<div class="container text-center mt-5">
<h1>Making Every Bride's dream come true</h1>
<h3>We are a brand that embodies the artistic connection in which a wedding dress holds.</h3>
<p>
    Allow us to play host to your full wedding fairy tale. We'll walk you through the day so that everything goes smoothly and you and your partner can relax and enjoy yourselves. Whether it's a civilian ceremony or a church ceremony in the chapel, we'll help you organize everything you'll need. We will also organize a wedding reception with selected culinary tastes according to your requests in our gorgeous setting.
</p>

</div>
{%endblock%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <title>{% block title%} Bridal Bliss {%endblock%}</title>
    {% block styles%}
    {{super}}
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
    {%endblock%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/iconify/2.0.0/iconify.min.js"></script>   
    {%endblock%}
</head>
</head>
<body>
<!-- Navbar -->
{% include "nav.html"%}

    <!-- Main Content -->
    {% block content %}
    
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/budget/budget.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}

    <div> 
        <div class=" row" >
                
            
            <div class="col-md-4 bg-light p-5 mx-auto my-4" id="postform">
                <h4 class="text-center mt-3 text-primary mb-2">Enter your budget</h4>
                {{wtf.quick_form(form)}}
            </div>
           
            {%if budgets%}

            {% for service in budgets.items %}
                    <div class="col-md-7 my-3 bg-light p-5 border rounded">
                        <hr>
                        <div class="row bg-light p-5">
                            <div class="col-md-2  text-center ">
                                    <img class=" blog-img me-10 d-block" style="clip-path: circle(); width: 75px;" src="{{ url_for('static', filename='images/' + service.user.profile_pic_path) }}">
                                    <!-- <p id="usern"><a href="{{url_for('main.',username = blog.user.username)}}"><span  style="color: blue"><strong>{{service.user.username}}</strong></span> </a> </p>  -->
                            </div>
                            <div class="col-md-10 pr-4 d-justify userblog">
                                <p class="text-success text-underline">Ksh {{service.cost}}</p>
                                <hr>
                                <a href="{{url_for('main.makeorder',serv_id = service.id)}}">Make Order</a>
                                <br>
                                <p>{{service.category}}</p>
                                <div><span><a  href="{{url_for('main.review')}}"></a>Review</span>
                                    <span class="text-danger ms-3">{{service.reviews|count}}</span>
                                </div>
                            </div>
                        </div> 
                        
                    </div>
                       
                {% endfor %}
            
        </div>



    </div>
    {%endif%}
   
{% endblock%}

app/templates/contacts.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Contact Us</title>
    <!-- MDB icon -->
    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
</head>

<body>
    <!-- Start your project here-->

    <div id="preview" class="preview">
        <div style="display: none;"></div>
        <div>
            <div data-draggable="true" class="" style="position: relative;" draggable="false">
                <!---->
                <section draggable="false" class="container pt-5" data-v-271253ee="">
                    <section class="mb-10">
                        <div class="row">
                            <div class="col-md-6 mb-4 mb-md-0">
                                <h2 class="fw-bold mb-4">Contact us</h2>
                                <p class="text-muted mb-4">Your wedding starts here! We have created this website as a convenient and interactive way to share all of the important details with you in the lead up to our wedding. Feel free to contact us by feeling this form.</p>
                                <p class="text-muted mb-2">Nairobi, Kenya</p>
                                <p class="text-muted mb-2">+254 711 223 344
                                    <p class="text-muted mb-2">bridalbliss@gmail.com</p>
                            </div>
                            <div class="col-md-6 mb-4 mb-md-0">
                                <form>
                                    <!-- Name input -->
                                    <div class="form-outline mb-4"> <input type="text" id="form4Example1" class="form-control"> <label class="form-label" for="form4Example1" style="margin-left: 0px;">Name</label>
                                        <div class="form-notch">
                                            <div class="form-notch-leading" style="width: 9px;"></div>
                                            <div class="form-notch-middle" style="width: 42.4px;"></div>
                                            <div class="form-notch-trailing"></div>
                                        </div>
                                    </div>
                                    <!-- Email input -->
                                    <div class="form-outline mb-4"> <input type="email" id="form4Example2" class="form-control"> <label class="form-label" for="form4Example2" style="margin-left: 0px;">Email address</label>
                                        <div class="form-notch">
                                            <div class="form-notch-leading" style="width: 9px;"></div>
                                            <div class="form-notch-middle" style="width: 88.8px;"></div>
                                            <div class="form-notch-trailing"></div>
                                        </div>
                                    </div>
                                    <!-- Message input -->
                                    <div class="form-outline mb-4"> <textarea class="form-control" id="form4Example3" rows="4"></textarea> <label class="form-label" for="form4Example3" style="margin-left: 0px;">Message</label>
                                        <div class="form-notch">
                                            <div class="form-notch-leading" style="width: 9px;"></div>
                                            <div class="form-notch-middle" style="width: 60px;"></div>
                                            <div class="form-notch-trailing"></div>
                                        </div>
                                    </div>
                                    <!-- Checkbox -->
                                    <div class="form-check d-flex justify-content-center mb-4"> <input class="form-check-input me-2" type="checkbox" value="" id="form4Example4" checked=""> <label class="form-check-label" for="form4Example4">Send me a copy of this message</label> </div>
                                    <!-- Submit button --><button type="submit" class="btn        btn-primary btn-block mb-4" aria-controls="#picker-editor">Send</button> </form>
                            </div>
                        </div>
                    </section>
                </section>
                <!---->
            </div>
        </div>
    </div>

    <!-- End your project here-->

    <!-- MDB -->
    <script type="text/javascript" src="js/mdb.min.js"></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>
</body>

</html>

app/templates/home.html
{%extends 'base.html'%}

{% block content%}

<div class="carousel-item">
    
</div>
</div>




{%endblock%}

app/templates/index.html
{%extends 'base.html'%} {% block content %} {% block content %}


<div class="container landing">
    {% for service in services.items %}
    <div class="row">

        <div class="card col-md-4 mb-2 mt-3" style="width: 40rem;">
            <img class="card-img-top" src="{{url_for('static', filename='images/cars.jpg')}}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{service.category}}</h5>
                <p class="card-text">Describe your choice of cars and we will deliver.</p>
            </div>
            <div class="card-footer">
                <a href="{{url_for('main.makeorder',serv_id = service.id)}}" class="btn btn-secondary">Make Order</a>
                <span><a  class="btn btn-secondary" href="{{url_for('main.review',serv_id=service.id)}}">Review</a></span>
                <span class="text-danger ms-3">{{service.all_reviews}}</span>
            </div>
        </div>
        {% endfor %} {% for page_num in services.iter_pages(left_edge = 1, right_edge = 1, left_current=1, right_current = 2) %} {% if page_num %} {% if services.page == page_num %}
        <a href="{{url_for('main.index',page = page_num)}}" class="btn btn-sm btn-secondary mb-2">{{ page_num }}</a> {% else%}
        <a href="{{url_for('main.index',page = page_num)}}" class="btn btn-sm btn-outline-secondary mb-2">{{ page_num }}</a> {% endif %} {% else%} ... {% endif %} {% endfor %}
    </div>
</div>



{%endblock%}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light ">
    <div class="container-fluid row">
        <div class="col-md-4">
            <h1>Bridal Bliss</h1>
        </div>
        <div class="col-md-8">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item p-3">
                        <a class="nav-link" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item p-3">
                        <a class="nav-link" href="/about.html">About us</a>
                    </li>
                    {%if current_user.is_authenticated%}
                    <li class="nav-item p-3">
                        <a class="nav-link" href="{{url_for('main.profile',name=current_user.username)}}">Profile</a>
                    </li>
                    </li>
                    <li class="nav-item p-3">
                        <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                    </li>
                    {%else%}
                    <li class="nav-item p-3">
                        <a class="nav-link" href="{{url_for('auth.signup')}}">Sign Up</a>
                    </li>
                    <li class="nav-item p-3">
                        <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
                    </li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </div>
</nav>

app/templates/orders/makeorder.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}

    <div> 
        <div class=" row" >
                
            <div class="col-md-2"></div>
            <div class="col-md-8 bg-light p-5 mx-auto my-4" id="postform">
                <h4 class="text-center mt-3 text-primary mb-2">Make a new order</h4>
                {{wtf.quick_form(form)}}
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
   
{% endblock%}

app/templates/orders/orders.html
{%extends 'base.html'%}

{%block content%}
<div class="bg-light mx-auto">
    {%if orders%}
<h6 class="text-center">Users Order details</h6>
<div>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Order ID</th>
            <th scope="col">Ordered by</th>
            <th scope="col">Order Date</th>
            
            <th scope="col">More Details</th>
            <th scope="col"> Remove</th>
          </tr>
        </thead>
        <tbody>
            {%for order in orders%}
          <tr>
            <th scope="row">{{order.id}}</th>
            <td>{{user.username}}</td>
            <td>{{order.order_date}}</td>
            
            <td>{{order.details}}</td>
            <td><a class="btn btn-danger" href="{{url_for('main.deleteorder',id=order.id)}}">Delete</a></td>
          </tr>
          {%endfor%}
         
        </tbody>
      </table>
</div>
{%endif%}
</div>
{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-4 black">
        <div class="content-section mt-4">
            {% for message in get_flashed_messages() %}
            <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
            </div>
            {% endfor %}
            {% if errors %}
              {% for error in errors %}
                <span class="text-danger">{{ error }}</span></br>
              {% endfor %}
            {%endif%}

     
            <div class="  my-4"><a class="btn  btn-outline-success d-block " id="ref" href="{{url_for('main.addservice',user_id=current_user.id)}}">Add a service +<i class="fa-solid fa-plus ms-2 text-success"></i></a></div>
    <div class="card testimonial-card">
    <div class="card-up indigo lighten-1"></div>
    <div class="avatar mx-auto white">
      <img src="{{profile_pic_path}}" class="rounded account-img mt-2" alt="default" style="clip-path: circle();">
    </div>
    <div class="card-body">
      <h4 class="card-title text-center">{{current_user.username|title}}</h4>
      <hr>
      <p> {{current_user.email}} </p>
      <p><i class="fas fa-quote-left"></i> {{current_user.bio}} <i class="fas fa-quote-right"></i> </p>
      <div class="my-4">
        <a  target="blank" class="btn btn-secondary" href="{{url_for('main.orders',user_id=current_user.id)}}">View My orders</a>
      </div>
      <button class="btn btn-sm btn-success" id="showform"> Update</button>
    </div>
      
      </div>
    </div>
  </div>
  <div class="col-md-6">
      <div class="container mt-4" >
        <div id="profileupdate">
          <h3 class="text-primary ">Profile Update</h3>
            {{wtf.quick_form(form)}}
        </div>
      </div>
  </div>
</div>
{% endblock %}

app/templates/reviews.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block content %}
<div class="container my-4">
    <div class="row">
        {% if all_reviews %}
        <div class="col-md-7">
            <h3 class="text-center">All reviews for this service</h3> {% for review in all_reviews %}
            <div class="card w-90 mb-3">
                <div class="card-body">
                    <h5>{{review.services.category}}</h5>
                    <p class="card-title">{{ review.review }}</p>
                    <p class="card-text">--- {{review.users.username}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-md-5  reviewform">
            {{wtf.quick_form(form)}}
        </div>
    </div>
    {% else %}
    <div class="card w-90 mb-3">
        <h2 class="card-body text-center">
            <p class="card-title">No reviews for this yet for this service. Would you like to make a review?</p>
        </h2>
    </div>
    <div class="col-md-5">
        {{wtf.quick_form(form)}}
    </div>
    {% endif %}
</div>
{% endblock %}

app/templates/service/addservice.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}

    <div> 
        <div class=" row" >
                
            <div class="col-md-2"></div>
            <div class="col-md-8 bg-light p-5 mx-auto my-4" id="postform">
                <h4 class="text-center mt-3 text-primary mb-2">Register a new service</h4>
                {{wtf.quick_form(form)}}
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>

{% endblock%}